version: '3.8'

services:
  app:
    build: .
    container_name: python-node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
